### PR TITLE
Minor refactor of tests that modify a state value

### PR DESCRIPTION
**Pull request by kberryUSGS**
This isn't a full refactor to use parameterized tests. Instead, for now, I removed a bunch of repeated code in tests that tweak a single state parameter's value and moved this to a function in the associated fixture. This is related to #104 in that it could be a first step in that direction, but doesn't fix it completely.

### CODE REVIEW

**Comment by Kelvinrr** [comment]
Pulled locally and testsed, looks like you're missing a class name? FrameIsdTest->FrameStateTest in on line 73 in FramePluginTests.cpp

**Comment by kberryUSGS** [comment]
@Kelvinrr Fixed!

**Comment by thareUSGS** [comment]
👍

**Comment by kberryUSGS** [comment]
@Kelvinrr Thanks :+1:

**Pull request merged**
