### PR TITLE
Merge of master into dev

### PR DESCRIPTION
**Pull request by kberryUSGS**
This includes the changes associated with #109, #110, and #112. 

I would like to do more "test cleanup" on the added tests added in this PR after this gets merged.

### CODE REVIEW

**Comment by kberryUSGS** [comment]
@Kelvinrr The errors on here are actually because I accidentally initially set up the PR to merge into master and then switched it to dev. As far as I can tell, the CI ran on the merge of this PR to master and that failed, but this is expected. As far as I know, CI is not yet set up to run on dev.

**Comment by Kelvinrr** [comment]
We can chat about it during the next stand up, but from poking around after pulling locally there seems to be some issues with parameter scaling in the test ISD. I imagine Master branch tests added expected certain values in one unit and Dev branch expected them in another.

**Comment by kberryUSGS** [comment]
@Kelvinrr Chatting about this sounds good. I'm curious what failures you're seeing that I'm not.

**Comment by kberryUSGS** [comment]
@Kelvinrr I'm still not seeing any test failures, even after cloning a 'clean' copy and building it. 

This is what I did to test this -- let me know if any of this looks incorrect to you: 

```
source activate CSM2 
git clone git@github.com:kberryUSGS/CSM-CameraModel.git
cd CSM-CameraModel/
git checkout dev 
git submodule update --init --recursive
mkdir build && cd build
cmake .. && make && ctest -VV
```

And I get lots of test output that ends in: 

```
100% tests passed, 0 tests failed out of 37

Total Test time (real) =   0.16 sec
```

**Comment by kberryUSGS** [comment]
The largest of differences between output and expected value from the CI tests are on the order of ~0.1 Not sure yet what is causing this on the CI build but not locally.

**Comment by kberryUSGS** [comment]
Okay, the test outputs are different and much worse on Mac than on Linux. Investigating why!

**Comment by kberryUSGS** [comment]
Tests are passing. The build failure is due to some problem with uploading the new build to anaconda cloud. See https://github.com/USGS-Astrogeology/CSM-CameraModel/issues/128

**Pull request merged**
