### PR TITLE
patched segfault error + added detector center as defined in json schema

### PR DESCRIPTION
**Pull request by Kelvinrr**
One last edit, noticed the last test failed due to a segfault, in hastily scanning the plugin member vars for things that should be 0 I accidentally passed 0.0 to std::vecotor::assign which should be a 10, essentially creating a 0 element vector.

### CODE REVIEW

**Comment by jessemapel** [comment]
I'm not sure why this is failing CI. Can you add the -VV flag to the ctest call in the travis file?

**Comment by jessemapel** [comment]
@Kelvinrr Nvm, just pull from master it has the -VV flag now.

**Comment by jessemapel** [comment]
Actually, this isn't even expected to pass tests still so I think it's ready to merge?

**Comment by Kelvinrr** [comment]
it's failing for the same reason I mentioned in the previous PR: there are some variables not defined in the ISD that imageToGround relies on and so they stay at 0, therefore the computed values are different.

**Comment by jessemapel** [comment]
Okay, this is ready to go then.

**Pull request merged**
